#indica la version de Docker Compose utilizada
version: '3.8'
#Bloque de servicios, indica los contenedores a utilizar.
services:
  mocky-app:       #nombre del servicio
    image: dreamy236/mocky-app-backend #imagen utilizada si viene del registro.
    ports:          #puertos que estaran expuestos.
      - ${PUERTO_APP}:8080
    env_file:
      - .env
    environment:    #variable de ambiente
      - NOMBRE_APP=$AMBIENTE
    networks:    #red para conectar los equipos.
      - red-app
    volumes:
      - my-volume-compose:${DB_VOLUME}
    depends_on:   #indica que primero debe subir los servicios indicados.
      - db
  
  db:
    image: buildo/h2database:latest
    ports:
      - ${DB_PORT}:8082
    env_file:
      - .env
    volumes:
      - volume:${DB_VOLUME}
    networks:
      - red-app
    
    
  front-mocky-app:
    image: dreamy236/mocky-app:latest
    network_mode: host
networks:  #bloque para las redes
  red-app:   #indicando la red definida

volumes: #Bloque para definir los volumenes
  my-volume-compose:
  volume: